### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by ConanMusk** [cnyvfang/CORUN-Colabator#2]
目前我有两个问题：
![image](https://github.com/user-attachments/assets/8642785f-7034-437b-bc0c-cf174dc0f68c)
目前我无法下载nima权重，您能否放在谷歌云盘一份？谢谢，我对您后面的质量评价部分很感兴趣。

![image](https://github.com/user-attachments/assets/453ff5ce-89b7-4d19-8679-6516fbfb2070)
这里的路径无法找到是我的编译器问题吗？

**Comment by cnyvfang** [comment]
Hi, Thank you for your interest.

For the first question, the pretrained weights of NIMA you can download from:  https://drive.google.com/file/d/10imGH6ylu0jJp4vTHYKZd8UZxvfq4OXa/view?usp=sharing, and https://drive.google.com/file/d/1Kn1z-gtWHmqTiotAXs8NiwpZKxdcQ7v2/view?usp=sharing
, and copy the weights to ~/.cache/torch/hub/pyiqa and ~/.cache/torch/hub/checkpoints (In order to be compatible with different versions of pyiqa.) 

For the second question, you should check if you initialize the environment, install the BasicSR we modified and our CORUN-Colabator in order and successfully. You should ensure that you have already 'cd' to the root folder (./CORUN-Colabator or ./CORUN-Colabator-main, case-sensitive) of our project before run the scripts.
